/* eslint-disable no-unused-vars */
import React from "react";
import { Link } from "react-scroll";

function PrivacyPolicy() {
  const sections = [
    {
      id: "introduction",
      title: "Privacy Policy – Safely360",
      content: `Last updated: October 29, 2024

This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.`,
    },
    {
      id: "interpretation-and-definitions",
      title: "Interpretation and Definitions",
      subsections: [
        {
          subtitle: "Interpretation",
          content: `The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.`,
        },
        {
          subtitle: "Definitions",
          content: `For the purposes of this Privacy Policy:

• Account means a unique account created for You to access our Service or parts of our Service.
• Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest, or other securities entitled to vote for election of directors or other managing authority.
• Application refers to Safely360, the software program provided by the Company.
• Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Safely360.
• Country refers to: Pakistan
• Device means any device that can access the Service such as a computer, a cellphone, or a digital tablet.
• Personal Data is any information that relates to an identified or identifiable individual.
• Service refers to the Application.
• Service Provider means any natural or legal person who processes the data on behalf of the Company.
• Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.
• You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.`,
        },
      ],
    },
    {
      id: "collecting-and-using-your-personal-data",
      title: "Collecting and Using Your Personal Data",
      subsections: [
        {
          subtitle: "Types of Data Collected",
          content: `Personal Data

While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
• Email address
• First name and last name
• Usage Data

Usage Data

Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's Internet Protocol address, browser type, browser version, pages visited, time and date of visits, time spent on pages, unique device identifiers, and other diagnostic data.

When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers, and other diagnostic data.

Information Collected while Using the Application

While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:
• Information regarding your location

We use this information to provide features of Our Service, to improve and customize Our Service. The information may be uploaded to the Company's servers and/or a Service Provider's server or it may be simply stored on Your device.

You can enable or disable access to this information at any time, through Your Device settings.`,
        },
      ],
    },
    {
      id: "use-of-your-personal-data",
      title: "Use of Your Personal Data",
      content: `The Company may use Personal Data for the following purposes:

• To provide and maintain our Service, including to monitor the usage of our Service.
• To manage Your Account: to manage Your registration as a user of the Service.
• For the performance of a contract: the development, compliance, and undertaking of contracts for products, items, or services.
• To contact You: via email, telephone, SMS, or other electronic communication regarding updates or security notifications.
• To provide You with news, special offers, and general information about services unless You have opted out.
• To manage Your requests: to attend and manage Your requests to Us.
• For business transfers: in case of mergers, restructuring, or acquisitions where Personal Data is transferred.
• For other purposes such as data analysis, usage trends, and marketing improvement.`,
    },
    {
      id: "sharing-your-personal-data",
      title: "Sharing Your Personal Data",
      content: `We may share Your personal information in the following situations:

• With Service Providers: To monitor and analyze the use of our Service, to contact You.
• For business transfers: In connection with any merger, sale, financing, or acquisition.
• With Affiliates: In which case we will require those affiliates to honor this Privacy Policy.
• With business partners: To offer You certain products, services, or promotions.
• With other users: If You share personal information in public areas.
• With Your consent: For any other purpose with Your explicit consent.`,
    },
    {
      id: "retention-of-your-personal-data",
      title: "Retention of Your Personal Data",
      content: `The Company will retain Your Personal Data only for as long as necessary for the purposes set out in this Privacy Policy.`,
    },
    {
      id: "transfer-of-your-personal-data",
      title: "Transfer of Your Personal Data",
      content: `Your information may be transferred to and maintained on computers located outside of Your jurisdiction where data protection laws may differ.`,
    },
    {
      id: "delete-your-personal-data",
      title: "Delete Your Personal Data",
      content: `You have the right to delete or request that We assist in deleting the Personal Data collected about You.`,
    },
    {
      id: "disclosure-of-your-personal-data",
      title: "Disclosure of Your Personal Data",
      subsections: [
        {
          subtitle: "Business Transactions",
          content: `If the Company is involved in a merger, acquisition, or asset sale, Your Personal Data may be transferred.`,
        },
        {
          subtitle: "Law Enforcement",
          content: `We may disclose Your Personal Data when required by law.`,
        },
      ],
    },
    {
      id: "security-of-your-personal-data",
      title: "Security of Your Personal Data",
      content: `The security of Your Personal Data is important to Us, but no method of transmission over the Internet is 100% secure.`,
    },
    {
      id: "childrens-privacy",
      title: "Children's Privacy",
      content: `Our Service does not address anyone under the age of 13. If We become aware of any Personal Data collected from children without parental consent, We take steps to remove that information.`,
    },
    {
      id: "links-to-other-websites",
      title: "Links to Other Websites",
      content: `Our Service may contain links to other websites. We strongly advise You to review the Privacy Policy of every site You visit.`,
    },
    {
      id: "changes-to-privacy-policy",
      title: "Changes to this Privacy Policy",
      content: `We may update Our Privacy Policy from time to time. We will notify You via email or a prominent notice prior to the change becoming effective.`,
    },
    {
      id: "contact-us",
      title: "Contact Us",
      content: `If you have any questions about this Privacy Policy, You can contact us:

By email: support@techwizardlabs.org`,
    },
  ];

  return (
    <div className="container mx-auto px-4 py-8 max-w-4xl">
      <h1 className="text-5xl font-bold mb-8 text-center mt-8">
        Privacy Policy
      </h1>

      {/* Table of Contents */}
      <div className="bg-base-200 rounded-lg p-6 mb-8">
        <h2 className="text-2xl font-semibold mb-4">Table of Contents</h2>
        <nav>
          <ul className="space-y-2">
            {sections.map((section) => (
              <li key={section.id}>
                <Link
                  to={section.id}
                  smooth={true}
                  duration={500}
                  className="cursor-pointer hover:text-primary"
                >
                  {section.title}
                </Link>
              </li>
            ))}
          </ul>
        </nav>
      </div>

      {/* Content Sections */}
      <div className="prose max-w-none">
        {sections.map((section) => (
          <section key={section.id} id={section.id} className="mb-12">
            <h2 className="text-3xl font-semibold mb-4">{section.title}</h2>
            {section.subsections ? (
              section.subsections.map((subsection, index) => (
                <div key={index} className="mb-6">
                  <h3 className="text-2xl font-medium mb-3">
                    {subsection.subtitle}
                  </h3>
                  <p className="whitespace-pre-line leading-relaxed">
                    {subsection.content}
                  </p>
                </div>
              ))
            ) : (
              <p className="whitespace-pre-line leading-relaxed">
                {section.content}
              </p>
            )}
          </section>
        ))}

        {/* Footer */}
        <div className="mt-8 pt-4 border-t text-sm text-gray-600">
          <p>Last updated: October 29, 2024</p>
          <p>© 2024 Safely360. All rights reserved.</p>
        </div>
      </div>
    </div>
  );
}

export default PrivacyPolicy;
